/**
 * Parameters the reader founded, as opposed to the ones the app ships with.
 *
 * The mapping screen used to offer two outcomes for a printed name it did not
 * recognise: merge it into an existing parameter, or leave it out of the
 * trends. Neither is right for a test the app has simply never heard of —
 * merging files it under the wrong heading, and leaving it out means the
 * reader's own lab result is invisible on the one screen built to show it.
 *
 * So a third outcome: the name becomes a parameter of its own.
 *
 * It cannot become one in `registry.json`, which is curated, generated by the
 * pipeline and identical for every account. It becomes one in the account's
 * own settings, and is added to the Registry at load time — after which it is
 * an analyte like any other: it gets a trend, it is offered in the picker so a
 * second lab's spelling can join it, and `Registry.match` finds it (with the
 * material guard intact) on the next report without a click.
 *
 * Two things a founded parameter deliberately does not get. It has no
 * labtestsonline.cz explainer, because that map is curated by hand with a
 * medical guarantor behind it and the UI already shows nothing for an id
 * absent from it. And it has no unit conversions, so a second lab printing the
 * same test in a different unit is not silently converted — the same as any
 * shipped analyte with no factor declared for that unit.
 *
 * Its reference interval is the one the lab printed on the reader's own
 * report, or — where no lab printed one — the figure they typed. Neither is
 * ever used to decide whether a result is abnormal: flags come from the
 * interval printed beside each individual measurement, in normalize.ts, and
 * nothing here reaches them. What the interval does is give `review.ts` one
 * consistent envelope for the misread-decimal check across every report filed
 * under the parameter, including a later one where the lab printed no interval
 * at all and the check would otherwise have nothing to work against.
 *
 * A typed interval is the reader's own figure, carries `rangeOrigin:
 * "manual"`, and is labelled that way wherever the app names a provenance. It
 * is never shown as something a lab stated.
 */
import type { AnalyteDef } from "./models";
import { stripMaterialPrefix } from "./normalize";
import { normKey } from "./registry";

/**
 * What the account stores. Deliberately narrower than `AnalyteDef`: the
 * synonyms live in the learned-mapping map, where every other accepted name
 * lives, and `material` is derived by the Registry from those synonyms rather
 * than authored.
 */
export interface CustomAnalyte {
  canonicalId: string;
  displayNameCs: string;
  canonicalUnit: string;
  /** The interval for this parameter, in `canonicalUnit`. Null when it has none. */
  referenceRange: [number, number] | null;
  /**
   * Where `referenceRange` came from: the report the parameter was founded
   * on, or the reader, who is offered the field only when no lab printed one.
   * Absent when there is no interval at all.
   */
  rangeOrigin?: "document" | "manual";
}

/** Founded ids carry a prefix so the stored blob and the CSV export say so. */
const PREFIX = "custom_";

/**
 * The name to offer for a printed one: "S_Feritin" → "Feritin".
 *
 * Only the material prefix comes off, and the case is left alone. The printed
 * name is the reader's best evidence of what the test is called, so this
 * tidies it rather than rewriting it — and the form lets them edit it anyway.
 */
export function defaultParameterName(rawName: string): string {
  return stripMaterialPrefix((rawName || "").trim()).trim();
}

/**
 * `custom_<slug>` from a display name, avoiding an id already in use.
 *
 * The slug comes from `normKey`, so it is diacritic-free and matches how the
 * registry keys names: "Feritin" and "feritín" would produce the same id, and
 * the second one gets a suffix rather than silently overwriting the first.
 */
export function customAnalyteId(displayName: string, taken: (id: string) => boolean): string {
  const slug = normKey(displayName).split(" ").filter(Boolean).join("_");
  const base = PREFIX + (slug || "parametr");
  if (!taken(base)) return base;
  for (let n = 2; ; n++) {
    const id = `${base}_${n}`;
    if (!taken(id)) return id;
  }
}

/** Whether an id is one the reader founded rather than one the app ships. */
export const isCustomAnalyteId = (canonicalId: string): boolean => canonicalId.startsWith(PREFIX);

/**
 * The parameter a proposed name would collide with, or null.
 *
 * Keyed on `normKey` — the same normalisation the matcher uses — so the check
 * catches the collisions that would actually matter: case, diacritics,
 * punctuation and a material prefix. Founding "Feritin" when a shipped
 * "Feritin" exists would give one test two trend lines, each with half the
 * history, and nothing on screen to say why.
 */
export function findExistingParameter(
  defs: Iterable<AnalyteDef>,
  displayName: string,
): AnalyteDef | null {
  const k = normKey(displayName);
  if (!k) return null;
  for (const d of defs) {
    if (normKey(d.displayNameCs) === k) return d;
    if (d.synonyms.some((s) => normKey(s) === k)) return d;
  }
  return null;
}

/** A registry entry from a stored founded parameter. */
export function toAnalyteDef(c: CustomAnalyte): AnalyteDef {
  return {
    canonicalId: c.canonicalId,
    displayNameCs: c.displayNameCs,
    // The founding printed name is a learned synonym, added by the same path
    // that records every other accepted mapping, so it is not repeated here.
    synonyms: [],
    canonicalUnit: c.canonicalUnit,
    unitConversions: {},
    referenceRange: c.referenceRange,
    // A stored parameter from before the field existed carries a document
    // interval — that was the only kind there was.
    ...(c.referenceRange === null ? {} : { rangeOrigin: c.rangeOrigin ?? "document" }),
  };
}
