/**
 * The synthetic laboratories under fixtures/labs/<lab>/ — a `report.pdf` with
 * a text layer and a hand-authored `truth.json` — read the way the portal's
 * text path reads a sheet, minus the model.
 *
 * Generated by tools/pipeline/scripts/make_lab_fixtures.py (Goal 2 of
 * docs/plans/multi-user.md). The truth is keyed on the printed name exactly
 * as this file yields it; `labs.test.ts` asserts the two sets are equal, and
 * tests/bench/mapping.bench.ts scores the catalog against the truth.
 *
 * What stands in for the reader: `candidateRows` says which printed rows are
 * measurements, and the name is `nameFromRow` anchored on the row's value —
 * the same call `interpretPage` makes with the value the reader returned.
 * Anchoring matters: without the value, a row whose result carries the lab's
 * own marker ("5,4 *") is named "K (Potassium) 5,4 * H", and an all-caps name
 * followed by a unit ("CHOL | 5,6 * | H | mmol/l") loses its name to the
 * section-label rule. The value is the first cell after the name whose
 * marker-stripped text is a number.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { NUMERIC_CELL, buildRows, candidateRows, nameFromRow, type Box, type TextRow } from "@bw/lab-core";

/** One truth entry: what a printed name is, and which id a careless mapper would pick. */
export interface TruthEntry {
  /** A catalog id, `NEW:<id>`, `NOT_BLOOD` or `IGNORE`. */
  answer: string;
  /** Ids a near-miss trap invites; a match onto one of them is scored "wrong". */
  wrong?: string[];
  /** The unit as printed. */
  unit: string;
  /** Why, in one line. */
  note: string;
}

export type Truth = Record<string, TruthEntry>;

/** A printed row the parser reads as a measurement. */
export interface PrintedRow {
  name: string;
  kind: "numeric" | "qualitative";
  page: number;
  index: number;
  rows: TextRow[];
}

/** Read `truth.json`; keys beginning with `_` are commentary, not names. */
export function readTruth(dir: string): Truth {
  const raw = JSON.parse(readFileSync(join(dir, "truth.json"), "utf-8")) as Record<string, unknown>;
  const out: Truth = {};
  for (const [k, v] of Object.entries(raw)) {
    if (k.startsWith("_")) continue;
    out[k] = v as TruthEntry;
  }
  return out;
}

/** The fixture directories, sorted, each holding a report.pdf. */
export function labFixtureDirs(root: string): string[] {
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(root, d.name, "report.pdf")))
    .map((d) => join(root, d.name))
    .sort();
}

/** pdf.js text items → the word boxes buildRows expects, in PDF units. */
export async function pdfPages(file: string): Promise<TextRow[][]> {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const data = new Uint8Array(readFileSync(file));
  const doc = await pdfjs.getDocument({ data, useSystemFonts: false }).promise;
  const pages: TextRow[][] = [];
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p);
    const content = await page.getTextContent();
    const viewport = page.getViewport({ scale: 1 });
    const words: Array<{ text: string; box: Box }> = [];
    for (const item of content.items as any[]) {
      const str: string = item.str ?? "";
      if (!str.trim()) continue;
      const [, , , , e, f] = item.transform as number[];
      const h = item.height ?? 10;
      const y0 = viewport.height - f - h;
      words.push({ text: str, box: [e, y0, e + (item.width ?? 0), y0 + h] });
    }
    pages.push(buildRows(words));
  }
  return pages;
}

const stripMarkers = (s: string) => s.replace(/[!*]/g, "").trim();

/** The row's value cell — the first after the name whose marker-stripped text is a number. */
function valueCell(row: TextRow): string | undefined {
  return row.cells.slice(1).find((c) => NUMERIC_CELL.test(stripMarkers(c)));
}

/** Every printed row the parser reads as a measurement, named as the portal would name it. */
export function printedRows(pages: TextRow[][]): PrintedRow[] {
  const out: PrintedRow[] = [];
  pages.forEach((rows, p) => {
    for (const c of candidateRows(rows)) {
      const name = c.kind === "numeric" ? nameFromRow(rows, c.index, valueCell(rows[c.index])) : c.name;
      out.push({ name, kind: c.kind, page: p + 1, index: c.index, rows });
    }
  });
  return out;
}
