/**
 * The four synthetic laboratories (fixtures/labs/<lab>/) hold together: every
 * printed row the parser reads has a truth entry, every truth entry is a row
 * the parser reads, and every answer is well-formed. Generated by
 * tools/pipeline/scripts/make_lab_fixtures.py; the bench in
 * tests/bench/mapping.bench.ts is what scores the catalog against them.
 *
 * This is the contract the bench relies on. A truth key nothing produces
 * would only ever be "missing", and a printed row without truth would be
 * scored by nobody — both are the fixture drifting from its generator.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { basename, dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { Registry, type AnalyteDef } from "@bw/lab-core";
import { labFixtureDirs, pdfPages, printedRows, readTruth } from "./labFixtures";

const HERE = dirname(fileURLToPath(import.meta.url));
const LABS = join(HERE, "fixtures", "labs");
const REGISTRY = join(HERE, "..", "..", "..", "apps", "portal", "public", "registry.json");

const ANSWER = /^(?:[a-z0-9_]+|NEW:[a-z0-9_]+|NOT_BLOOD|IGNORE)$/;

describe("the synthetic laboratories", () => {
  const dirs = labFixtureDirs(LABS);

  it("has all four labs", () => {
    expect(dirs.map((d) => basename(d))).toEqual(["konvent", "lis", "slovak", "wellness"]);
  });

  for (const dir of dirs) {
    describe(basename(dir), () => {
      it("keys the truth on exactly the names the parser yields", async () => {
        const truth = readTruth(dir);
        const printed = printedRows(await pdfPages(join(dir, "report.pdf"))).map((r) => r.name);
        expect(new Set(printed).size, "a printed name twice would make the truth ambiguous").toBe(printed.length);
        expect(printed.sort()).toEqual(Object.keys(truth).sort());
      });

      it("labels every row with a well-formed answer, and every catalog answer with a real id", () => {
        const defs = JSON.parse(readFileSync(REGISTRY, "utf-8")) as AnalyteDef[];
        const registry = new Registry(defs);
        const truth = readTruth(dir);
        const classes = { catalog: 0, new: 0, notBlood: 0, ignore: 0, traps: 0 };
        for (const [name, t] of Object.entries(truth)) {
          expect(t.answer, name).toMatch(ANSWER);
          if (t.answer === "NOT_BLOOD") classes.notBlood += 1;
          else if (t.answer === "IGNORE") classes.ignore += 1;
          else if (t.answer.startsWith("NEW:")) {
            classes.new += 1;
            expect(registry.get(t.answer.slice(4)), `${name}: NEW:${t.answer} is already in the catalog`).toBeUndefined();
          } else {
            classes.catalog += 1;
            expect(registry.get(t.answer), `${name}: ${t.answer} is not a catalog id`).toBeDefined();
          }
          if (t.wrong?.length) classes.traps += 1;
          for (const w of t.wrong ?? []) expect(w, `${name}: wrong id ${w}`).toMatch(/^[a-z0-9_]+$/);
        }
        // Every lab prints rows of all four classes and at least six traps.
        expect(classes.catalog).toBeGreaterThan(0);
        expect(classes.new).toBeGreaterThan(0);
        expect(classes.notBlood).toBeGreaterThan(0);
        expect(classes.ignore).toBeGreaterThan(0);
        expect(classes.traps).toBeGreaterThanOrEqual(6);
      });
    });
  }
});
