/**
 * The Czech change summary. This is prose a doctor reads, generated by
 * deterministic templates precisely so no interpretive or diagnostic language
 * can appear — these tests pin both the numbers and the wording.
 */
import { describe, expect, it } from "vitest";
import { czExact, czNum, summarizeChanges, summarizeTrend } from "../src/lib/summary";
import type { Trend, TrendPoint } from "../src/lib/trends";

const pt = (date: string, value: number | null, flag: TrendPoint["flag"], lo = 4.11, hi = 5.6): TrendPoint => ({
  date,
  value,
  unit: "mmol/l",
  flag,
  refLow: lo,
  refHigh: hi,
  valueRaw: value === null ? "<1,0" : String(value).replace(".", ","),
  reportId: "r",
  suspect: null,
});

const trend = (points: TrendPoint[], name = "Glukóza"): Trend => ({
  canonicalId: "glukoza",
  displayName: name,
  unit: "mmol/l",
  points,
});

describe("czNum", () => {
  it("uses a Czech decimal comma and trims trailing noise", () => {
    expect(czNum(5.4)).toBe("5,4");
    expect(czNum(114)).toBe("114");
    expect(czNum(0.443)).toBe("0,443");
  });

  it("renders a missing value as a dash rather than zero", () => {
    expect(czNum(null)).toBe("—");
    expect(czNum(undefined)).toBe("—");
  });
});

describe("summarizeTrend", () => {
  it("describes a rise with its absolute and relative change", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 6.0, "high")]))!;
    expect(r.text).toContain("5 → 6");
    expect(r.text).toContain("+1");
    expect(r.text).toContain("+20 %");
  });

  it("uses no verb, so no analyte can disagree with it grammatically", () => {
    // "Triacylglyceroly vzrostlo" (should be "vzrostly") was the failure this
    // avoids: the subject comes from a 109-entry registry of mixed gender.
    const r = summarizeTrend(
      trend([pt("2024-01-01", 1.98, "normal"), pt("2025-01-01", 2.31, "high")], "Triacylglyceroly"),
    )!;
    for (const verb of ["vzrostlo", "kleslo", "vzrostly", "klesly", "vzrostla", "klesla"]) {
      expect(r.text).not.toContain(verb);
    }
  });

  it("says a value has newly left the reference range", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 6.0, "high")]))!;
    expect(r.text).toContain("nově nad rozmezím");
    expect(r.outOfRange).toBe(true);
  });

  it("distinguishes staying out of range from newly leaving it", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 6.5, "high"), pt("2025-01-01", 7.0, "high")]))!;
    expect(r.text).toContain("stále nad rozmezím");
  });

  it("says a value has returned into range", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 3.0, "low"), pt("2025-01-01", 5.0, "normal")]))!;
    expect(r.text).toContain("nově v rozmezí");
  });

  it("does not claim 'no change' beside two visibly different numbers", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 142, "normal", 137, 145), pt("2025-01-01", 141, "normal", 137, 145)]))!;
    expect(r.text).toContain("prakticky beze změny");
    expect(r.text).toContain("−1");
    expect(r.changed).toBe(false);
  });

  it("rounds the percentage to a whole number", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 6.0, "high"), pt("2025-01-01", 7.0, "high")]))!;
    expect(r.text).toContain("+17 %");
    expect(r.text).not.toContain("16,67");
  });

  it("returns nothing when there is only one numeric result to compare", () => {
    expect(summarizeTrend(trend([pt("2024-01-01", 5.0, "normal")]))).toBeNull();
  });

  it("ignores censored points, which carry no number to compare", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", null, "unknown")]));
    expect(r).toBeNull();
  });

  it("never uses interpretive or diagnostic language", () => {
    const r = summarizeTrend(trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 9.0, "high")]))!;
    for (const word of ["diabetes", "riziko", "nemoc", "doporučuj", "pravděpodobně", "znamená"]) {
      expect(r.text.toLowerCase()).not.toContain(word);
    }
  });
});

describe("summarizeChanges", () => {
  it("puts out-of-range analytes first, then bigger relative moves", () => {
    const trends = new Map<string, Trend>([
      ["a", trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 5.2, "normal")], "Klidný")],
      ["b", trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 9.0, "high")], "Vysoký")],
      ["c", trend([pt("2024-01-01", 5.0, "normal"), pt("2025-01-01", 5.9, "normal")], "Střední")],
    ]);
    expect(summarizeChanges(trends).map((r) => r.displayName)).toEqual(["Vysoký", "Střední", "Klidný"]);
  });

  it("skips trends that cannot be compared instead of inventing a record", () => {
    const trends = new Map<string, Trend>([["a", trend([pt("2024-01-01", 5.0, "normal")])]]);
    expect(summarizeChanges(trends)).toEqual([]);
  });
});

describe("czExact", () => {
  it("shows the value exactly as printed, without rounding", () => {
    // czNum would render this as "3,8" — two different numbers for one
    // measurement in a tool whose pitch is checking against the source.
    expect(czExact(3.802, "3,802")).toBe("3,802");
    expect(czNum(3.802)).toBe("3,8");
  });

  it("keeps a censored value verbatim", () => {
    expect(czExact(null, "<1,0")).toBe("<1,0");
  });

  it("falls back to the number when nothing was printed", () => {
    expect(czExact(5.32, "")).toBe("5,32");
    expect(czExact(null, "")).toBe("—");
  });
});
